### PR TITLE
Redo the bottom toolbar to be more responsive using flexbox

### PR DESCRIPTION
**Pull request by albertchae**
Main things I changed
- Change the DOM structure so it actually represents the order of the elements showing on screen
- Instead of `position: absolute`, use padding/margin to get elements to show with right spacing. In the rare case where we had to position something outside of flexbox, use relative/absolute depending on whether we wanted the element to take up its layout space or not. With the volume slider, we had to set an ancestor div to `position: relative` so that the volume slider's absolute would position itself relative to it.
- Remove a few cases of resizing things via javascript

### CODE REVIEW

**Comment by captainexpo** [comment]
The only things that I can see that are a problem is the junction between the expression envelope and the controls bar is missing, and the time slider ticks are positioned weird. Also, the control bar scales when the equation gets too tall, and it looks pretty weird.

**Comment by albertchae** [comment]
@Captainexpo-1 Thanks for checking

- I'll fix the position of the junction
- re: time slider ticks, what's the intended layout? I noticed it goes from 0 to roughly 7-9 depending on the width of the screen
- Can you link me a level where the equation is tall and scales the control bar? I can fix that too

**Comment by captainexpo** [comment]
okay, well just for the scale of the control bar it's not really about the level, more what the user inputs. Although, it's only when the equation gets unreasonably high. E.G.
Screen Shot 2023-04-18 at 7 24 52 PM

And for the time slider ticks this is what they should look like: 
Screen Shot 2023-04-18 at 7 26 33 PM


Thanks for doing this!

**Comment by albertchae** [comment]
@Captainexpo-1 I think I addressed those issues in https://github.com/Captainexpo-1/sinerider/pull/1/commits/74e807133d062e6a2a7a01022803e794705bf98e, can you check again when you have a chance? I also fixed the helper bubble position in the commit after.

**Comment by captainexpo** [comment]
Looks great! Merged!

**Pull request merged**
